FROM jupyter/base-notebook:latest
MAINTAINER Mauro Mussin mauro.mussin@gmail.com

USER root
RUN apt update
RUN apt-get install -y software-properties-common
RUN add-apt-repository universe 
RUN apt-get install -y git
RUN apt-get install -y libgeos-dev
USER jovyan